-- Removed false positive drop statements/disable RLS generated by supabase db diff (policies managed by srtd)
CREATE TABLE public.temp_calls (id uuid DEFAULT gen_random_uuid() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
ALTER TABLE public.temp_calls ADD CONSTRAINT temp_calls_pkey PRIMARY KEY (id);
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.temp_calls TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.temp_calls TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.temp_calls TO service_role;
