-- Generated by `supabase db diff -f fix_reviews_grants`.
-- Diff tool emitted false-positive DROP POLICY statements above because it
-- doesn't know that policies are owned by srtd, not schemas — removed per
-- the source-of-truth split (see .claude/AGENTS.md).

GRANT INSERT, SELECT ON public.reviews TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.reviews TO authenticated;